[package]
version = "0.1.0"
name = "fibonacci-script"
edition = "2021"

[dependencies]
itertools = "0.12.1"
sp1-sdk = { git = "https://github.com/succinctlabs/sp1.git" }
sha2 = "0.10.8"

[build-dependencies]
sp1-helper = { git = "https://github.com/succinctlabs/sp1.git" }
