# https://docs.celestia.org/nodes/docker-images
# --volume == -v [local path]:[container path]
# docker run [args...] -v $HOME/my-node-store:/home/celestia \
#     celestia $NODE_TYPE init [args...]
# docker run -e NODE_TYPE=$NODE_TYPE -e P2P_NETWORK=$NETWORK \
#     -v $HOME/my-node-store:/home/celestia \
#     ghcr.io/celestiaorg/celestia-node:v0.13.5 \
#     celestia light init --p2p.network $NETWORK

name: celestia
services:
  celestia:
    image: ghcr.io/celestiaorg/celestia-node:v0.13.5
    environment:
      - NODE_TYPE=light
      - P2P_NETWORK=mainnet
    volumes:
      - $HOME/my-node-store:/home/celestia
    command: celestia light init --p2p.network $P2P_NETWORK